### ISSUE TITLE
Fixed Distance Buffer Link Down

### ISSUE THREAD

**Issue by auchers** [UrbanSystemsLab/spatial-join-mongodb#2]
Link leads to 404 error. 

Might also be useful to flesh out more specifics of buffer if we think this will be relevant for other cities.

**Comment by jaskiratr** [comment]
Can we look into gdal tools as an alternative to create the buffer via command line?

**Comment by auchers** [comment]
Good idea. I’ll try to look into it!

**Comment by auchers** [comment]
looks like a [good lead](https://qgis.org/api/2.18/classQgsGeometryAnalyzer.html#a98c32a39818e6956cb8dcd6aaf43cf96) -- will keep diggind

[example usage](https://gis.stackexchange.com/questions/204553/create-individual-buffers-from-vector-points-in-qgis)

**Comment by jaskiratr** [comment]
If we need to prepare a script. Turf library is also an option for Javascript stack. 

https://github.com/Turfjs/turf/tree/master/packages/turf-buffer

**Comment by jaskiratr** [comment]
Fixed the link
